/** Source: US_States_and_Cities_List.csv — major cities per state */
export const US_STATE_CITY_ROWS: { state: string; cities: string[] }[] = [
  { state: "Alabama", cities: ["Birmingham", "Montgomery", "Mobile", "Huntsville"] },
  { state: "Alaska", cities: ["Anchorage", "Juneau", "Fairbanks", "Sitka"] },
  { state: "Arizona", cities: ["Phoenix", "Tucson", "Mesa", "Scottsdale"] },
  { state: "Arkansas", cities: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale"] },
  {
    state: "California",
    cities: ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Fresno"],
  },
  { state: "Colorado", cities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins"] },
  { state: "Connecticut", cities: ["Bridgeport", "Stamford", "New Haven", "Hartford"] },
  { state: "Delaware", cities: ["Wilmington", "Dover", "Newark", "Middletown"] },
  {
    state: "Florida",
    cities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Tallahassee", "St. Petersburg"],
  },
  { state: "Georgia", cities: ["Atlanta", "Augusta", "Columbus", "Savannah"] },
  { state: "Hawaii", cities: ["Honolulu", "Hilo", "Kailua", "Kapolei"] },
  { state: "Idaho", cities: ["Boise", "Meridian", "Nampa", "Idaho Falls"] },
  { state: "Illinois", cities: ["Chicago", "Aurora", "Rockford", "Naperville"] },
  { state: "Indiana", cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"] },
  { state: "Iowa", cities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City"] },
  { state: "Kansas", cities: ["Wichita", "Overland Park", "Kansas City", "Topeka"] },
  { state: "Kentucky", cities: ["Louisville", "Lexington", "Bowling Green", "Owensboro"] },
  { state: "Louisiana", cities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"] },
  { state: "Maine", cities: ["Portland", "Lewiston", "Bangor", "South Portland"] },
  {
    state: "Maryland",
    cities: ["Baltimore", "Frederick", "Gaithersburg", "Germantown", "Rockville"],
  },
  { state: "Massachusetts", cities: ["Boston", "Worcester", "Springfield", "Cambridge"] },
  { state: "Michigan", cities: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights"] },
  { state: "Minnesota", cities: ["Minneapolis", "St. Paul", "Rochester", "Duluth"] },
  { state: "Mississippi", cities: ["Jackson", "Gulfport", "Southaven", "Biloxi"] },
  { state: "Missouri", cities: ["Kansas City", "St. Louis", "Springfield", "Columbia"] },
  { state: "Montana", cities: ["Billings", "Missoula", "Great Falls", "Bozeman"] },
  { state: "Nebraska", cities: ["Omaha", "Lincoln", "Bellevue", "Grand Island"] },
  { state: "Nevada", cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas"] },
  { state: "New Hampshire", cities: ["Manchester", "Nashua", "Concord", "Derry"] },
  { state: "New Jersey", cities: ["Newark", "Jersey City", "Paterson", "Elizabeth"] },
  { state: "New Mexico", cities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe"] },
  {
    state: "New York",
    cities: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"],
  },
  { state: "North Carolina", cities: ["Charlotte", "Raleigh", "Greensboro", "Durham"] },
  { state: "North Dakota", cities: ["Fargo", "Bismarck", "Grand Forks", "Minot"] },
  { state: "Ohio", cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo"] },
  { state: "Oklahoma", cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"] },
  { state: "Oregon", cities: ["Portland", "Salem", "Eugene", "Gresham"] },
  { state: "Pennsylvania", cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie"] },
  { state: "Rhode Island", cities: ["Providence", "Warwick", "Cranston", "Pawtucket"] },
  {
    state: "South Carolina",
    cities: ["Charleston", "Columbia", "North Charleston", "Mount Pleasant"],
  },
  { state: "South Dakota", cities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings"] },
  { state: "Tennessee", cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga"] },
  {
    state: "Texas",
    cities: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington"],
  },
  { state: "Utah", cities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan"] },
  { state: "Vermont", cities: ["Burlington", "South Burlington", "Rutland", "Barre"] },
  { state: "Virginia", cities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond"] },
  { state: "Washington", cities: ["Seattle", "Spokane", "Tacoma", "Vancouver"] },
  { state: "West Virginia", cities: ["Charleston", "Huntington", "Morgantown", "Parkersburg"] },
  { state: "Wisconsin", cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha"] },
  { state: "Wyoming", cities: ["Cheyenne", "Casper", "Laramie", "Gillette"] },
];

export const US_STATE_ABBR: Record<string, string> = {
  Alabama: "AL",
  Alaska: "AK",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  Florida: "FL",
  Georgia: "GA",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MS",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Pennsylvania: "PA",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  Virginia: "VA",
  Washington: "WA",
  "West Virginia": "WV",
  Wisconsin: "WI",
  Wyoming: "WY",
};

/** Rough regional color for copy variation */
export const US_STATE_REGION: Record<string, string> = {
  Maine: "New England",
  "New Hampshire": "New England",
  Vermont: "New England",
  Massachusetts: "New England",
  "Rhode Island": "New England",
  Connecticut: "New England",
  "New York": "Mid-Atlantic",
  "New Jersey": "Mid-Atlantic",
  Pennsylvania: "Mid-Atlantic",
  Delaware: "Mid-Atlantic",
  Maryland: "Mid-Atlantic",
  Virginia: "Mid-Atlantic",
  "West Virginia": "Appalachia",
  "North Carolina": "Southeast",
  "South Carolina": "Southeast",
  Georgia: "Southeast",
  Florida: "Southeast",
  Alabama: "Southeast",
  Mississippi: "Southeast",
  Tennessee: "Southeast",
  Kentucky: "Southeast",
  Louisiana: "Gulf South",
  Arkansas: "South Central",
  Oklahoma: "South Central",
  Texas: "South Central",
  Ohio: "Midwest",
  Indiana: "Midwest",
  Illinois: "Midwest",
  Michigan: "Midwest",
  Wisconsin: "Midwest",
  Minnesota: "Upper Midwest",
  Iowa: "Midwest",
  Missouri: "Midwest",
  "North Dakota": "Northern Plains",
  "South Dakota": "Northern Plains",
  Nebraska: "Great Plains",
  Kansas: "Great Plains",
  Montana: "Mountain West",
  Wyoming: "Mountain West",
  Colorado: "Mountain West",
  "New Mexico": "Southwest",
  Arizona: "Southwest",
  Utah: "Mountain West",
  Nevada: "Southwest",
  Idaho: "Pacific Northwest interior",
  Washington: "Pacific Northwest",
  Oregon: "Pacific Northwest",
  California: "West Coast",
  Alaska: "Alaska",
  Hawaii: "Pacific islands",
};
